name: 'Build & push'

on:
  push:
    tags:
      - 'ofw-*'
      - 'unlshd-*'
      - 'RM*'
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
      # Generate aux information
      - name: Generate aux variables
        id: aux
        run: |
          ref_tag=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##")
          echo firmware_version=$(echo $ref_tag | sed -e "s#\(ofw-\)\?##") >> $GITHUB_OUTPUT
          echo image=f0-firmware:$ref_tag >> $GITHUB_OUTPUT
          
          # Determine firmware type
          firmware_typere="^([A-Za-z]+)([0-9]+)?-.*"
          if [[ $ref_tag =~ $firmware_typere ]]; then
            firmware_type="${BASH_REMATCH[1]^^}"
          fi

          if [[ -z "$firmware_type" ]]; then
            echo The type of firmware could not be determined. Check the tag!
            exit 1
          fi

          echo firmware_type="$firmware_type" >> $GITHUB_OUTPUT
      # Get docker metadata
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ steps.aux.outputs.image }}
      # Login into repository package manager
      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build and push docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          build-args: | 
            firmware_repo=${{ vars[format('{0}_REPO_URL', steps.aux.outputs.firmware_type)] }}
            firmware_version=${{ steps.aux.outputs.firmware_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
